# Generated by Django 4.0 on 2021-12-19 08:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery_app.album')),
                ('tag', models.ManyToManyField(to='gallery_app.Tag')),
            ],
        ),
    ]
