# Generated by Django 4.0 on 2021-12-19 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='picture',
            options={'ordering': ['-perks']},
        ),
        migrations.AddField(
            model_name='picture',
            name='perks',
            field=models.IntegerField(default=0),
        ),
    ]
