# Generated by Django 4.0 on 2021-12-19 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery_app', '0002_alter_picture_options_picture_perks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='album',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gallery_app.album'),
        ),
    ]
